// Code generated by Kitex v0.4.4. DO NOT EDIT.

package relationfunc

import (
	"context"
	api "douSheng/cmd/relation/kitex_gen/api"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	RelationAction(ctx context.Context, token string, toUserId int64, state int32, callOptions ...callopt.Option) (r *api.RelationResponse, err error)
	FollowList(ctx context.Context, userId int64, token string, callOptions ...callopt.Option) (r *api.RelationResponse, err error)
	FollowerList(ctx context.Context, userId int64, token string, callOptions ...callopt.Option) (r *api.RelationResponse, err error)
	FriendList(ctx context.Context, userId int64, token string, callOptions ...callopt.Option) (r *api.RelationResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kRelationFuncClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kRelationFuncClient struct {
	*kClient
}

func (p *kRelationFuncClient) RelationAction(ctx context.Context, token string, toUserId int64, state int32, callOptions ...callopt.Option) (r *api.RelationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RelationAction(ctx, token, toUserId, state)
}

func (p *kRelationFuncClient) FollowList(ctx context.Context, userId int64, token string, callOptions ...callopt.Option) (r *api.RelationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowList(ctx, userId, token)
}

func (p *kRelationFuncClient) FollowerList(ctx context.Context, userId int64, token string, callOptions ...callopt.Option) (r *api.RelationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowerList(ctx, userId, token)
}

func (p *kRelationFuncClient) FriendList(ctx context.Context, userId int64, token string, callOptions ...callopt.Option) (r *api.RelationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FriendList(ctx, userId, token)
}
