// Code generated by Kitex v0.4.4. DO NOT EDIT.

package commentfunc

import (
	"context"
	api "douSheng/cmd/comment/kitex_gen/api"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CommentList(ctx context.Context, videoId int64, token string, callOptions ...callopt.Option) (r *api.CommentResponse, err error)
	AddCommentAction(ctx context.Context, token string, actionType int32, text string, videoId int64, callOptions ...callopt.Option) (r *api.CommentResponse, err error)
	DeleteCommentAction(ctx context.Context, token string, actionType int32, commentId int64, videoId int64, callOptions ...callopt.Option) (r *api.CommentResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kCommentFuncClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCommentFuncClient struct {
	*kClient
}

func (p *kCommentFuncClient) CommentList(ctx context.Context, videoId int64, token string, callOptions ...callopt.Option) (r *api.CommentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommentList(ctx, videoId, token)
}

func (p *kCommentFuncClient) AddCommentAction(ctx context.Context, token string, actionType int32, text string, videoId int64, callOptions ...callopt.Option) (r *api.CommentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddCommentAction(ctx, token, actionType, text, videoId)
}

func (p *kCommentFuncClient) DeleteCommentAction(ctx context.Context, token string, actionType int32, commentId int64, videoId int64, callOptions ...callopt.Option) (r *api.CommentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteCommentAction(ctx, token, actionType, commentId, videoId)
}
