// Code generated by Kitex v0.4.4. DO NOT EDIT.

package echo

import (
	"context"
	api "douSheng/kitex/kitex_gen/api"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Video(ctx context.Context, req *api.Video, callOptions ...callopt.Option) (r *api.Response, err error)
	User(ctx context.Context, req *api.User, callOptions ...callopt.Option) (r *api.Response, err error)
	FriendUser(ctx context.Context, req *api.FriendUser, callOptions ...callopt.Option) (r *api.Response, err error)
	Comment(ctx context.Context, req *api.Comment, callOptions ...callopt.Option) (r *api.Response, err error)
	UserVideoFavorite(ctx context.Context, req *api.UserVideoFavorite, callOptions ...callopt.Option) (r *api.Response, err error)
	Relation(ctx context.Context, req *api.Relation, callOptions ...callopt.Option) (r *api.Response, err error)
	Message(ctx context.Context, req *api.Message, callOptions ...callopt.Option) (r *api.Relation, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kEchoClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kEchoClient struct {
	*kClient
}

func (p *kEchoClient) Video(ctx context.Context, req *api.Video, callOptions ...callopt.Option) (r *api.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Video(ctx, req)
}

func (p *kEchoClient) User(ctx context.Context, req *api.User, callOptions ...callopt.Option) (r *api.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.User(ctx, req)
}

func (p *kEchoClient) FriendUser(ctx context.Context, req *api.FriendUser, callOptions ...callopt.Option) (r *api.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FriendUser(ctx, req)
}

func (p *kEchoClient) Comment(ctx context.Context, req *api.Comment, callOptions ...callopt.Option) (r *api.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Comment(ctx, req)
}

func (p *kEchoClient) UserVideoFavorite(ctx context.Context, req *api.UserVideoFavorite, callOptions ...callopt.Option) (r *api.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserVideoFavorite(ctx, req)
}

func (p *kEchoClient) Relation(ctx context.Context, req *api.Relation, callOptions ...callopt.Option) (r *api.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Relation(ctx, req)
}

func (p *kEchoClient) Message(ctx context.Context, req *api.Message, callOptions ...callopt.Option) (r *api.Relation, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Message(ctx, req)
}
